version: "3.7"

services:
  nest_app:
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_URL=mongodb://nest_db
      - PORT=5000
    volumes:
      - ./src:/nest_app/src
    networks:
      - common

  db:
    image: mongo
    container_name: nest_db
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - common

volumes:
  mongodata:

networks:
  common:
    driver: bridge
